version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/bio/
  - source: /connect.php
    destination: /var/www/bio/
  - source: /biodata.php
    destination: /var/www/bio/
  - source: /bio.sql
    destination: /var/www/bio/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
